### PR TITLE
Site Now Uses Middleman

### PR DESCRIPTION
**Pull request by zankavrogin**
Site is now powered by middleman, the blog posts have their own page, the code has been refactored and cleaned up, and a new page called Contribute has been added.

### CODE REVIEW

**Comment by deadprogram** [comment]
Reviewing the structure, seems to me all the blog posts should be in a /blog directory, that there should be a link in the top menu to "Blog", and that the homepage should at most show the most recent 3 posts, and possibly just the most recent post.

**Comment by zankavrogin** [comment]
Does the navigation look good here? I made the items a little smaller because the nav looked a bit crammed with the extra blog link. 
Is there anything else I should change?

**Comment by deadprogram** [comment]
Looks good. Can we please have a link on homepage below the newest blog posts "More posts"

**Comment by deadprogram** [comment]
We need the `rake` task added so we can deploy this. I suggest a new PR off of master, please.

**Comment by MarioRicalde** [comment]
Just pushed it.

**Comment by MarioRicalde** [comment]
Feel free to build whenever.

**Comment by deadprogram** [comment]
```
$ bx rake publish
rake aborted!
cannot load such file -- middleman-gh-pages
/home/ron/Development/kidsruby/kidsruby-site/Rakefile:1:in `require'
/home/ron/Development/kidsruby/kidsruby-site/Rakefile:1:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by deadprogram** [comment]
@MarioRicalde see the problem I just had?

**Comment by deadprogram** [comment]
@zankavrogin & @MarioRicalde when I run `rake build` I get this error:

```
$ bx rake publish
rake aborted!
cannot load such file -- middleman-gh-pages
/home/ron/Development/kidsruby/kidsruby-site/Rakefile:1:in `require'
/home/ron/Development/kidsruby/kidsruby-site/Rakefile:1:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by zankavrogin** [comment]
@RoverWire Could this be because there is no 'middleman-gh-pages' gem?

**Comment by solojavier** [comment]
I tested running without bundle exec and it worked... seems like "rake" and "middleman-gh-pages" is not part of the bundle... adding them would solve the issue, want me to push that change?

**Comment by MarioRicalde** [comment]
seems like the guys didn't place the `middleman-gh-pages` declaration in the `Gemfile`. Added and pushed.

**Pull request merged**
